### ISSUE TITLE
Use a crash report system for the GCS

### ISSUE THREAD

**Issue by guilhermito** [TauLabs/TauLabs#1217]
Google's breakpad (https://code.google.com/p/google-breakpad/) looks like a good choice, and there are some examples on how to include it on a Qt multi-platform aplication.

**Comment by mlyle** [comment]
Possible for endomorphism release.  PR #1802

**Comment by mlyle** [comment]
Deferred.  Just not quite ready and past functional deadline.

**Comment by PTDreamer** [comment]
Not quite ready? It has been functional for days!?! You have a broken system that was messing your compile process, others tested it and it worked. Also since day one that this doesn't break anything which  wasn't already broken, the last stuff I have added was cosmetic stuff (which you say doesn't work although I tested it, maybe something wrong with your network since it also needs more than 10secs to send a dump.
Fuck it, I'm closing that PR.
