### ISSUE TITLE
Quanton Vbatfix move PC15 to PC5

### ISSUE THREAD

**Issue by bektorkhan** [TauLabs/TauLabs#1387]
I have modified my Quanton board to fix the design error in rev 1 where Vbat is connected to PC15 instead of PC5 that it pobably was intended.

Since it was not connected before this should do it... Quanton pios_board.h:

-------------------------------- snip ---------------------------------------
```
//-------------------------
// ADC
//-------------------------
#define PIOS_ADC_SUB_DRIVER_MAX_INSTANCES 3

// PIOS_ADC_PinGet(0) = IN7
// PIOS_ADC_PinGet(1) = IN8
// PIOS_ADC_PinGet(5) = VBAT
//-------------------------
#define PIOS_DMA_PIN_CONFIG \
{ \
{ GPIOA, GPIO_Pin_0, ADC_Channel_0 }, \
{ GPIOA, GPIO_Pin_1, ADC_Channel_1 }, \
{ NULL, 0, ADC_Channel_Vrefint }, /* Voltage reference */ \
{ NULL, 0, ADC_Channel_TempSensor }, /* Temperature sensor */ \
{ NULL, 0, ADC_Channel_TempSensor }, /* Temperature sensor */ \
{ GPIOC, GPIO_Pin_5, ADC_Channel_15 }, \
}

/* we have to do all this to satisfy the PIOS_ADC_MAX_SAMPLES define in pios_adc.h */
/* which is annoying because this then determines the rate at which we generate buffer turnover events */
/* the objective here is to get enough buffer space to support 100Hz averaging rate */
#define PIOS_ADC_NUM_CHANNELS 6
#define PIOS_ADC_MAX_OVERSAMPLING 2
#define PIOS_ADC_USE_ADC2 0

#define VREF_PLUS	3.3
```
----------------------------- snip ----------------------------------------

Don't really know why the Tempsensor is repeated, but for compatibility I don't change anything.

I have tested it and Vbat is available at ADC5 with a scale about 90,55 mv/V for my quanton board!

I am new to all this and don't get howto push/commit in git.. sorry.

**Comment by kubark42** [comment]
@bektorkhan, thanks a lot for this. Sorry to be so late. Would you like help making this into a git commit?

**Comment by bektorkhan** [comment]
@kubark42 ,  yes I need help, or someone to do it!!

**Comment by kubark42** [comment]
@bektorkhan, great! So glad you're still out there. So let's start with a bit of background work:

* Do you already have the repository cloned and these changes made?
* Which operating system are you using?
* Are you comfortable with the command line?
* Is the above code all the changes you had to make?

**Comment by bektorkhan** [comment]
@kubark42 

Q1: Not the new ChibiOS version.. 
Q2: Have to check, I think I ran the VM somewhere, I have multiple Windows 7-8, Centos 6.5 main server , Ubuntu..
Q3: Yepp
Q4: I think so, might be an analog read call for Vbat on this new ADC instance somewhere.. have to check. Hope I find it!!

Obs! This will only work if you mod the Quanton board and move the Vbat from PC15 to PC5 (fix the design error)

**Comment by bektorkhan** [comment]
I found two modified versions.. the one below is for only Vbat fix.. I think I have also modified the buzzer on my board to get another ADC input to get AirSpeed & Sonar (I think was my thought was Landing assist from Sonar) but thats not for common users maybe..
One on master-20141026 as follows:
//-------------------------
// ADC
//-------------------------
#define PIOS_ADC_SUB_DRIVER_MAX_INSTANCES       3

// PIOS_ADC_PinGet(0) = IN7
// PIOS_ADC_PinGet(1) = IN8
// PIOS_ADC_PinGet(2) = BAT
//-------------------------
#define PIOS_DMA_PIN_CONFIG                                                                   \
{                                                                                             \
	{ GPIOA, GPIO_Pin_0,     ADC_Channel_0 },                                                 \
	{ GPIOA, GPIO_Pin_1,     ADC_Channel_1 },                                                 \
	{ GPIOC, GPIO_Pin_5,     ADC_Channel_2 },                                                 \
	{ NULL,  0,              ADC_Channel_Vrefint },           /* Voltage reference */         \
	{ NULL,  0,              ADC_Channel_TempSensor },        /* Temperature sensor */        \
	{ NULL,  0,              ADC_Channel_TempSensor },        /* Temperature sensor */        \
}

/* we have to do all this to satisfy the PIOS_ADC_MAX_SAMPLES define in pios_adc.h */
/* which is annoying because this then determines the rate at which we generate buffer turnover events */
/* the objective here is to get enough buffer space to support 100Hz averaging rate */
#define PIOS_ADC_NUM_CHANNELS           6
#define PIOS_ADC_MAX_OVERSAMPLING       2
#define PIOS_ADC_USE_ADC2               0

#define VREF_PLUS			3.3

**Comment by kubark42** [comment]
> This will only work if you mod the Quanton board and move the Vbat from PC15 to PC5 (fix the design error)

Since it's a hardware bug, it seems reasonable to fix what we can in software and then @lilvinz can instruct users on how to make the physical mod. I see a greater value in this, since many people will feel comfortable making a simple board mod.

If you have any pictures here that you can post those would be helpful.

===========================

WIth that code snippet, we're really close to making this work. Open up the git bash shell, navigate to the directory where you have the code, and type ```git checkout -b quanton_adc_fix```. This will create a new "branch" and let you operate out of that branch. Now type ```git gui```. You should get a program that opens up and see something similar to the following screenshot:

![screen shot 2015-10-03 at 8 16 39 am](https://cloud.githubusercontent.com/assets/1118185/10262850/2886f022-69a7-11e5-8182-8137389abc7d.png)

(Don't mind that you're missing some files in the top left corner, those ones that are white are not tracked by git and are local to my computer.)

```git gui``` helps you understand the changes you're going to make, as well as provide for a convenient button to get those changes commited and pushed upstream.

For starters, you can right-click in the diff field and choose to stage "hunks" or "lines". You can also click on the blue icon in the upper left corner to stage the entire changeset for that file. Here's where you can fine tune what you're committing. Notice as you stage lines, hunks, entire files that the lower left corner pane updates. Basically, whatever is in the lower left corner is going to be committed when you click the "Commit" button. But before pushing that button... 

You will need to write a commit message. The commit message has a particular form, and you can read about it at https://github.com/TauLabs/TauLabs/pull/1920#issuecomment-138323411. However, if you don't have the time to read that I'd suggest the following:

```
Quanton: Add ADC support for battery

The Quanton board has a known schematic bug where the ADC pin (PC5) is not connected to the battery terminal. This updates the software to support battery readings over PC5.

Note: this requires a hardware modification to work. The connection to PC15 must be cut and replaced by a connection to PC5.
```

From there, once you have stages all your lines of code and added the commit message, you can click "Commit". You'll notice that all the stages changes disappeared from the bottom left pane. Don't panic, this is normal! Your changes are now in your local branch. The next thing to do is click "Push". You'll get a dialog, but you don't have to change anything here right now so just click "Push" a second time. You might get a few dialogs asking for login and password. 

Once everything is done, you should have a green message saying that the push was successful. Great! Once you get this far, drop back in here and I'll give you a quick tutorial on creating a merge request to get your changes submitted to the main Tau Labs repository.

P.S. Since you use Windows #1961 might interest you, which should make setting up Windows development environments much simpler.

**Comment by bektorkhan** [comment]
@kubark42 info on HW mod is in the forum
:
http://forum-test.taulabs.org/viewtopic.php?f=20&t=145
