### ISSUE TITLE
GCS: PicoC Widget Button to transmit Test Value

### ISSUE THREAD

**Issue by cGiesen** [TauLabs/TauLabs#1404]
To transmit Test Value to FC we must use the browser for today.
It would be nice to auto transmit the value when change in GCS or have a transmit button

**Comment by Trex4Git** [comment]
I have done a quick implementation. Compiles and works in a first test.Before making a PR some Feedback would be nice.

![gcs_testvalue_send2](https://cloud.githubusercontent.com/assets/9142182/8192889/8d24a38e-1471-11e5-829b-e2248c062c63.png)

**Comment by Trex4Git** [comment]
Instead a text button, a icon ToolButton with an already existing and used icon:

![gcs_testvalue_send3](https://cloud.githubusercontent.com/assets/9142182/8195000/ac8b96ac-147f-11e5-911f-922e448a63f8.png)

**Comment by Trex4Git** [comment]
As alternative 2 new Icons. Interested in your opinion.

![up_edit](https://cloud.githubusercontent.com/assets/9142182/8251933/3b71878e-1681-11e5-908b-5bc18f5089eb.png) or ![refresh_edit](https://cloud.githubusercontent.com/assets/9142182/8251936/468b005a-1681-11e5-81ac-c491e173e1ac.png)

**Comment by Trex4Git** [comment]
Icon 1 was my favorite, mainly because of better consistency with the other icons in the Widget.

But for better looking in the real widget i had to change small things.
When there is no more feedback i think i will make a pull request with this.

![gcs_picoc_send_testvalue_2](https://cloud.githubusercontent.com/assets/9142182/8291534/86fb7a56-192a-11e5-91d7-ecccbd1061d0.png)

**Comment by Trex4Git** [comment]
Created a pull request: https://github.com/TauLabs/TauLabs/pull/1686

**Comment by mlyle** [comment]
Resolved by #1686.
