### ISSUE TITLE
gcs crashes under OSX

### ISSUE THREAD

**Issue by ernieift** [TauLabs/TauLabs#1420]
gcs crashes with a clean quanton board in Config Gadget at Output. The fresh actuator settings are ChannelMin=ChannelMax=ChannelNeutral=1000. The startup screen shows the min and max values but the slider is empty. If you move the mouse over the screen, gcs crashes somewhere at ::getSliderInfo(). If you set ChannelMax=1001 in the data browser, all is fine.

**Comment by peabody124** [comment]
Does this happen with a release build or something you compiled locally? Is it the same debug stack as this? https://bugreports.qt-project.org/browse/QTBUG-43398?page=com.atlassian.streams.streams-jira-plugin:activity-stream-issue-tab

Point at the slider? I can get the tooltip for me. Have you tried with next at Qt 5.4?
![screen shot 2014-12-31 at 6 08 45 pm](https://cloud.githubusercontent.com/assets/618346/5591289/21adf632-9118-11e4-8508-0315ad457ebf.png)

**Comment by ernieift** [comment]
The screen is the same. But I don't even get a tool tip. There is only a beach ball for some seconds and the this:
...
Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_ARITHMETIC (SIGFPE)
Exception Codes:       EXC_I386_DIV (divide by zero)

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   org.qt-project.QtWidgets      	0x00000001067fd17c QMacStylePrivate::getSliderInfo(QStyle::ComplexControl, QStyleOptionSlider const*, HIThemeTrackDrawInfo*, QWidget const*) const + 460
1   org.qt-project.QtWidgets      	0x0000000106811ddf QMacStyle::subControlRect(QStyle::ComplexControl, QStyleOptionComplex const*, QStyle::SubControl, QWidget const*) const + 143
2   libCore_debug.dylib           	0x000000010f408d8d ManhattanStyle::subControlRect(QStyle::ComplexControl, QStyleOptionComplex const*, QStyle::SubControl, QWidget const*) const + 45 (manhattanstyle.cpp:177)
3   org.qt-project.QtWidgets      	0x00000001068d3b95 QStyleSheetStyle::subControlRect(QStyle::ComplexControl, QStyleOptionComplex const*, QStyle::SubControl, QWidget const*) const + 4805
4   org.qt-project.QtWidgets      	0x00000001069a2541 QSliderPrivate::newHoverControl(QPoint const&) + 385
5   org.qt-project.QtWidgets      	0x00000001069a2be0 QSlider::event(QEvent*) + 288
6   org.qt-project.QtWidgets      	0x0000000106823dbb QApplicationPrivate::notify_helper(QObject*, QEvent*) + 251
7   org.qt-project.QtWidgets      	0x00000001068239a1 QApplicationPrivate::dispatchEnterLeave(QWidget*, QWidget*, QPointF const&) + 1953
8   org.qt-project.QtWidgets      	0x00000001068246d0 QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) + 880

.....

Seems to be an bug within Qt5.4. It is the same project and the same Qt on both systems. The 10.8 works and the 10.10.1 not.

**Comment by elafargue** [comment]
Reproduced in current 'next', I will investigate.

**Comment by ernieift** [comment]
We can the actuatorsettings.xml like in #1424. This were a workaround. I think the error is in Qt5.4.

**Comment by elafargue** [comment]
OK, the interesting bit here is that if slidermin == slidermax, then you will notice that no text appears in the slider handle which indicates trouble already. Qt is definitely to blame, though of course a slider with Min==Max does not really make sense either.

Would it be acceptable to change the defaults of the ActuatorsSettings UAVObject for something more sensible than 1000 everywhere? I understand the safety implications thought, but the most important is to have a low neutral and defaults to a disarmed frame IMHO.... Similar to what you are proposing in your previous comment, @ernieift .

Another approach is to ensure Min != Max in the output configuration as a general rule. The same goes for every location where there is a range (including input settings). This is what I like best, since it prevents crashes in case a user creates an UAVObject setting where Min==Max.

Your thoughts?

**Comment by peabody124** [comment]
I think that makes the most sense. I implemented it in #1443 if you guys want to test it. The previous OSX doesn't crash with it.

**Comment by elafargue** [comment]
@peabody124 looks very sensible to me, I like the disabling approach. I will test first and then merge the PR if that's OK...

**Comment by ernieift** [comment]
fixed in #1443 .
