### ISSUE TITLE
allow control of throttle in positionhold mode

### ISSUE THREAD

**Issue by tofly1990** [TauLabs/TauLabs#1444]
when set "throttlecontrol = true" ,the alttitude is hold there ,but cant chontrol it. can we separate  the alttitude control from ph mode ,and use the ah mode to control it?

**Comment by OhmEye** [comment]
I agree this would be useful, it seems somewhat obvious to me that adjusting altitude while otherwise maintaining position can be desireable. Basically, an "elevator" mode seems like a great thing for videography at least. Park it where you want it and only deal with altitude while running a gimbal cam?

**Comment by mlyle** [comment]
Waiting for #1679 to land so I can work on this in a subsequent trivial PR.

**Comment by peabody124** [comment]
@mlyle that will be nice
