### ISSUE TITLE
Issues with next TL7_5_15

### ISSUE THREAD

**Issue by pug398** [TauLabs/TauLabs#1709]
PFD does not report # of satellites correctly. Instead of numbers has strange characters. Reported correctly in System>Satellite widget but not in PFD GPS sat count. Reported PDOP and ACC ok. Started last few releases and config files deleted and reinstalled. Opengl32.dll installed and graphics have been working fine. Windows error on closing of GCS appears fixed. Looked back and seems to have started with 6_20_15 release.

**Comment by mlyle** [comment]
Yes.  I believe this is a bug / limitation in QML that QT 5.5.0 may be expected to fix.  Before we had two PFD implementations-- the C implementation and the javascript/qml future one;  I removed the old one and there are definitely some regressions / limitations in functionality there because it seems QML can't get to some types.

**Comment by pug398** [comment]
Ok Mike. Just wanted to make sure that it was known and didn't get overlooked before going to release. Looks like the other issues I ran into have been resolved.

**Comment by mlyle** [comment]
Believed to be resolved.
